// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(BlockselfFFI)
import BlockselfFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_blockself_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_blockself_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureBlockselfInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterTimestamp: FfiConverterRustBuffer {
    typealias SwiftType = Date

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Date {
        let seconds: Int64 = try readInt(&buf)
        let nanoseconds: UInt32 = try readInt(&buf)
        // Build the Date from whole seconds first, then add the nanoseconds as a
        // separate TimeInterval.  Date stores CFAbsoluteTime (seconds since 2001),
        // so adding a small fraction to the ~7.8e8 base is twice as precise as
        // adding it to the ~1.76e9 Unix-epoch value, because the smaller magnitude
        // leaves more mantissa bits for the sub-second part.
        if seconds >= 0 {
            return Date(timeIntervalSince1970: Double(seconds))
                .addingTimeInterval(Double(nanoseconds) / 1.0e9)
        } else {
            return Date(timeIntervalSince1970: Double(seconds))
                .addingTimeInterval(-Double(nanoseconds) / 1.0e9)
        }
    }

    public static func write(_ value: Date, into buf: inout [UInt8]) {
        var delta = value.timeIntervalSince1970
        var sign: Int64 = 1
        if delta < 0 {
            // The nanoseconds portion of the epoch offset must always be
            // positive, to simplify the calculation we will use the absolute
            // value of the offset.
            sign = -1
            delta = -delta
        }
        if delta.rounded(.down) > Double(Int64.max) {
            fatalError("Timestamp overflow, exceeds max bounds supported by Uniffi")
        }
        let seconds = Int64(delta)
        let nanoseconds = UInt32((delta - Double(seconds)) * 1.0e9)
        writeInt(&buf, sign * seconds)
        writeInt(&buf, nanoseconds)
    }
}




public protocol ClientProtocol: AnyObject, Sendable {
    
    func host() async throws  -> Host
    
    func hostId()  -> UInt32
    
    func userId()  -> UInt32
    
}
open class Client: ClientProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_blockself_fn_clone_client(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_blockself_fn_free_client(handle, $0) }
    }

    
public static func login(username: String, password: String, hostId: UInt32?)async throws  -> Client  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_blockself_fn_constructor_client_login(FfiConverterString.lower(username),FfiConverterString.lower(password),FfiConverterOptionUInt32.lower(hostId)
                )
            },
            pollFunc: ffi_blockself_rust_future_poll_u64,
            completeFunc: ffi_blockself_rust_future_complete_u64,
            freeFunc: ffi_blockself_rust_future_free_u64,
            liftFunc: FfiConverterTypeClient_lift,
            errorHandler: FfiConverterTypeHttpError_lift
        )
}
    

    
open func host()async throws  -> Host  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_blockself_fn_method_client_host(
                        self.uniffiCloneHandle()
                )
            },
            pollFunc: ffi_blockself_rust_future_poll_rust_buffer,
            completeFunc: ffi_blockself_rust_future_complete_rust_buffer,
            freeFunc: ffi_blockself_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeHost_lift,
            errorHandler: FfiConverterTypeHttpError_lift
        )
}
    
open func hostId() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_blockself_fn_method_client_host_id(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
open func userId() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_blockself_fn_method_client_user_id(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeClient: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Client

    public static func lift(_ handle: UInt64) throws -> Client {
        return Client(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Client) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Client {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Client, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClient_lift(_ handle: UInt64) throws -> Client {
    return try FfiConverterTypeClient.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClient_lower(_ value: Client) -> UInt64 {
    return FfiConverterTypeClient.lower(value)
}




public struct Closure: Equatable, Hashable {
    public var id: UInt32
    public var canBook: Bool
    public var canPay: Bool
    public var from: Date
    public var to: Date

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: UInt32, canBook: Bool, canPay: Bool, from: Date, to: Date) {
        self.id = id
        self.canBook = canBook
        self.canPay = canPay
        self.from = from
        self.to = to
    }

    

    
}

#if compiler(>=6)
extension Closure: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeClosure: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Closure {
        return
            try Closure(
                id: FfiConverterUInt32.read(from: &buf), 
                canBook: FfiConverterBool.read(from: &buf), 
                canPay: FfiConverterBool.read(from: &buf), 
                from: FfiConverterTimestamp.read(from: &buf), 
                to: FfiConverterTimestamp.read(from: &buf)
        )
    }

    public static func write(_ value: Closure, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.id, into: &buf)
        FfiConverterBool.write(value.canBook, into: &buf)
        FfiConverterBool.write(value.canPay, into: &buf)
        FfiConverterTimestamp.write(value.from, into: &buf)
        FfiConverterTimestamp.write(value.to, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClosure_lift(_ buf: RustBuffer) throws -> Closure {
    return try FfiConverterTypeClosure.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClosure_lower(_ value: Closure) -> RustBuffer {
    return FfiConverterTypeClosure.lower(value)
}


public struct Configuration: Equatable, Hashable {
    public var website: String
    public var email: String
    public var minimumMealToPay: UInt8?
    public var motd: String?
    public var hideHistory: Bool
    public var closures: [Closure]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(website: String, email: String, minimumMealToPay: UInt8?, motd: String?, hideHistory: Bool, closures: [Closure]) {
        self.website = website
        self.email = email
        self.minimumMealToPay = minimumMealToPay
        self.motd = motd
        self.hideHistory = hideHistory
        self.closures = closures
    }

    

    
}

#if compiler(>=6)
extension Configuration: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConfiguration: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Configuration {
        return
            try Configuration(
                website: FfiConverterString.read(from: &buf), 
                email: FfiConverterString.read(from: &buf), 
                minimumMealToPay: FfiConverterOptionUInt8.read(from: &buf), 
                motd: FfiConverterOptionString.read(from: &buf), 
                hideHistory: FfiConverterBool.read(from: &buf), 
                closures: FfiConverterSequenceTypeClosure.read(from: &buf)
        )
    }

    public static func write(_ value: Configuration, into buf: inout [UInt8]) {
        FfiConverterString.write(value.website, into: &buf)
        FfiConverterString.write(value.email, into: &buf)
        FfiConverterOptionUInt8.write(value.minimumMealToPay, into: &buf)
        FfiConverterOptionString.write(value.motd, into: &buf)
        FfiConverterBool.write(value.hideHistory, into: &buf)
        FfiConverterSequenceTypeClosure.write(value.closures, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConfiguration_lift(_ buf: RustBuffer) throws -> Configuration {
    return try FfiConverterTypeConfiguration.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConfiguration_lower(_ value: Configuration) -> RustBuffer {
    return FfiConverterTypeConfiguration.lower(value)
}


public struct Establishment: Equatable, Hashable {
    public var name: String
    public var street: String
    public var postalCode: String
    public var city: String
    public var phoneNumber: String
    public var currencySymbol: String
    public var configuration: Configuration

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, street: String, postalCode: String, city: String, phoneNumber: String, currencySymbol: String, configuration: Configuration) {
        self.name = name
        self.street = street
        self.postalCode = postalCode
        self.city = city
        self.phoneNumber = phoneNumber
        self.currencySymbol = currencySymbol
        self.configuration = configuration
    }

    

    
}

#if compiler(>=6)
extension Establishment: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEstablishment: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Establishment {
        return
            try Establishment(
                name: FfiConverterString.read(from: &buf), 
                street: FfiConverterString.read(from: &buf), 
                postalCode: FfiConverterString.read(from: &buf), 
                city: FfiConverterString.read(from: &buf), 
                phoneNumber: FfiConverterString.read(from: &buf), 
                currencySymbol: FfiConverterString.read(from: &buf), 
                configuration: FfiConverterTypeConfiguration.read(from: &buf)
        )
    }

    public static func write(_ value: Establishment, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.street, into: &buf)
        FfiConverterString.write(value.postalCode, into: &buf)
        FfiConverterString.write(value.city, into: &buf)
        FfiConverterString.write(value.phoneNumber, into: &buf)
        FfiConverterString.write(value.currencySymbol, into: &buf)
        FfiConverterTypeConfiguration.write(value.configuration, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEstablishment_lift(_ buf: RustBuffer) throws -> Establishment {
    return try FfiConverterTypeEstablishment.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEstablishment_lower(_ value: Establishment) -> RustBuffer {
    return FfiConverterTypeEstablishment.lower(value)
}


public struct Host: Equatable, Hashable {
    public var id: UInt32
    public var localId: UInt32
    public var disabled: Bool
    public var establishment: Establishment
    public var firstName: String
    public var lastName: String
    public var mode: Mode
    public var quality: String
    public var division: String
    public var mealPrice: UInt16
    public var accountType: AccountType
    public var cardNumber: String?
    public var permissions: Permissions

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: UInt32, localId: UInt32, disabled: Bool, establishment: Establishment, firstName: String, lastName: String, mode: Mode, quality: String, division: String, mealPrice: UInt16, accountType: AccountType, cardNumber: String?, permissions: Permissions) {
        self.id = id
        self.localId = localId
        self.disabled = disabled
        self.establishment = establishment
        self.firstName = firstName
        self.lastName = lastName
        self.mode = mode
        self.quality = quality
        self.division = division
        self.mealPrice = mealPrice
        self.accountType = accountType
        self.cardNumber = cardNumber
        self.permissions = permissions
    }

    

    
}

#if compiler(>=6)
extension Host: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHost: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Host {
        return
            try Host(
                id: FfiConverterUInt32.read(from: &buf), 
                localId: FfiConverterUInt32.read(from: &buf), 
                disabled: FfiConverterBool.read(from: &buf), 
                establishment: FfiConverterTypeEstablishment.read(from: &buf), 
                firstName: FfiConverterString.read(from: &buf), 
                lastName: FfiConverterString.read(from: &buf), 
                mode: FfiConverterTypeMode.read(from: &buf), 
                quality: FfiConverterString.read(from: &buf), 
                division: FfiConverterString.read(from: &buf), 
                mealPrice: FfiConverterUInt16.read(from: &buf), 
                accountType: FfiConverterTypeAccountType.read(from: &buf), 
                cardNumber: FfiConverterOptionString.read(from: &buf), 
                permissions: FfiConverterTypePermissions.read(from: &buf)
        )
    }

    public static func write(_ value: Host, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.id, into: &buf)
        FfiConverterUInt32.write(value.localId, into: &buf)
        FfiConverterBool.write(value.disabled, into: &buf)
        FfiConverterTypeEstablishment.write(value.establishment, into: &buf)
        FfiConverterString.write(value.firstName, into: &buf)
        FfiConverterString.write(value.lastName, into: &buf)
        FfiConverterTypeMode.write(value.mode, into: &buf)
        FfiConverterString.write(value.quality, into: &buf)
        FfiConverterString.write(value.division, into: &buf)
        FfiConverterUInt16.write(value.mealPrice, into: &buf)
        FfiConverterTypeAccountType.write(value.accountType, into: &buf)
        FfiConverterOptionString.write(value.cardNumber, into: &buf)
        FfiConverterTypePermissions.write(value.permissions, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHost_lift(_ buf: RustBuffer) throws -> Host {
    return try FfiConverterTypeHost.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHost_lower(_ value: Host) -> RustBuffer {
    return FfiConverterTypeHost.lower(value)
}


public struct Permissions: Equatable, Hashable {
    public var payment: Bool
    public var reservation: Bool
    public var cafeteria: Bool
    public var bookWithNegativeBalance: Bool
    public var maxPassages: UInt8?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(payment: Bool, reservation: Bool, cafeteria: Bool, bookWithNegativeBalance: Bool, maxPassages: UInt8?) {
        self.payment = payment
        self.reservation = reservation
        self.cafeteria = cafeteria
        self.bookWithNegativeBalance = bookWithNegativeBalance
        self.maxPassages = maxPassages
    }

    

    
}

#if compiler(>=6)
extension Permissions: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePermissions: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Permissions {
        return
            try Permissions(
                payment: FfiConverterBool.read(from: &buf), 
                reservation: FfiConverterBool.read(from: &buf), 
                cafeteria: FfiConverterBool.read(from: &buf), 
                bookWithNegativeBalance: FfiConverterBool.read(from: &buf), 
                maxPassages: FfiConverterOptionUInt8.read(from: &buf)
        )
    }

    public static func write(_ value: Permissions, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.payment, into: &buf)
        FfiConverterBool.write(value.reservation, into: &buf)
        FfiConverterBool.write(value.cafeteria, into: &buf)
        FfiConverterBool.write(value.bookWithNegativeBalance, into: &buf)
        FfiConverterOptionUInt8.write(value.maxPassages, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePermissions_lift(_ buf: RustBuffer) throws -> Permissions {
    return try FfiConverterTypePermissions.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePermissions_lower(_ value: Permissions) -> RustBuffer {
    return FfiConverterTypePermissions.lower(value)
}



public enum AccountType: Equatable, Hashable {
    
    case student
    case commensal
    case teacher





}

#if compiler(>=6)
extension AccountType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAccountType: FfiConverterRustBuffer {
    typealias SwiftType = AccountType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AccountType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .student
        
        case 2: return .commensal
        
        case 3: return .teacher
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AccountType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .student:
            writeInt(&buf, Int32(1))
        
        
        case .commensal:
            writeInt(&buf, Int32(2))
        
        
        case .teacher:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAccountType_lift(_ buf: RustBuffer) throws -> AccountType {
    return try FfiConverterTypeAccountType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAccountType_lower(_ value: AccountType) -> RustBuffer {
    return FfiConverterTypeAccountType.lower(value)
}



public 
enum HttpError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case UrlParsing(message: String)
    
    case Request(message: String)
    
    case Serialize(message: String)
    
    case Unauthenticated(message: String)
    
    case PoisonedSession(message: String)
    
    case InvalidStatus(message: String)
    

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension HttpError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHttpError: FfiConverterRustBuffer {
    typealias SwiftType = HttpError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HttpError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .UrlParsing(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .Request(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .Serialize(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .Unauthenticated(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .PoisonedSession(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .InvalidStatus(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: HttpError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .UrlParsing(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .Request(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .Serialize(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .Unauthenticated(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .PoisonedSession(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .InvalidStatus(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHttpError_lift(_ buf: RustBuffer) throws -> HttpError {
    return try FfiConverterTypeHttpError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHttpError_lower(_ value: HttpError) -> RustBuffer {
    return FfiConverterTypeHttpError.lower(value)
}



public enum Mode: Equatable, Hashable {
    
    case cash
    case plan





}

#if compiler(>=6)
extension Mode: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMode: FfiConverterRustBuffer {
    typealias SwiftType = Mode

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Mode {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .cash
        
        case 2: return .plan
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Mode, into buf: inout [UInt8]) {
        switch value {
        
        
        case .cash:
            writeInt(&buf, Int32(1))
        
        
        case .plan:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMode_lift(_ buf: RustBuffer) throws -> Mode {
    return try FfiConverterTypeMode.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMode_lower(_ value: Mode) -> RustBuffer {
    return FfiConverterTypeMode.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt8: FfiConverterRustBuffer {
    typealias SwiftType = UInt8?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt8.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt8.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeClosure: FfiConverterRustBuffer {
    typealias SwiftType = [Closure]

    public static func write(_ value: [Closure], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeClosure.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Closure] {
        let len: Int32 = try readInt(&buf)
        var seq = [Closure]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeClosure.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureBlockselfInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_blockself_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_blockself_checksum_method_client_host() != 55644) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_blockself_checksum_method_client_host_id() != 15629) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_blockself_checksum_method_client_user_id() != 34465) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_blockself_checksum_constructor_client_login() != 57686) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureBlockselfInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all